const express=require("express")
const app=express()
const bodyparser=require("body-parser")
app.use(bodyparser.json())
const getRoutes=require("./routes/getMethods")
const ssr=require("./routes/handlebars")
const jde=require("./routes/jadeEngine")
const signup=require("./routes/signUp")
const signin=require("./routes/signIn")
app.set("view engine","jade")
app.use("/",getRoutes)
app.use("/",ssr)
app.use("/",jde)
app.use("/",signup)
app.use("/",signin)
app.listen(3000,()=>{
    console.log("server started")
})